### ISSUE TITLE
Please remove News checking

### ISSUE THREAD

**Issue by MichaelLawrenceDee** [taurgis/MiniCoder#1]
I know that you're no longer maintaining this project but I've continued using it with workarounds, until now. I've encountered this error upon startup

```
Error Starting up. (System, The remote server returned an error: (403) Forbidden., System.Collections.ListDictionaryInternal, System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at MiniCoder.External.Tools.fillPackages()
   at MiniCoder.External.Tools..ctor(Boolean load)
   at MiniCoder.GUI.MainForm.mainForm_Load(Object sender, EventArgs e))

```

I've also noticed that the previous static list in "News" have no longer shown up, I assume that this check is what's causing the error. A fix, or even a suggestion how to fix it would suffice.

**Comment by MichaelLawrenceDee** [comment]
I figured it out after using Red Gate's Reflector and Reflexil
